Add assert true hitter rule
volodya-lombrozo/jtcop pull request #249
Opened 2023-07-27 18:57 UTC by l3r8yJ

closes #242 

@volodya-lombrozo take a look, please

---

## PR-Codex overview
This PR focuses on adding line hitter functionality to the code. 

### Detailed summary
- Added `RuleLineHitter` to the list of rules in `RuleCorrectTestCase`
- Added `isLineHitter` method to `AssertionOfJavaParser`, `AssertionOfJUnit`, and `AssertionOfHamcrest`
- Added `assertTrueHitter` and `assertFalseHitter` methods to `AssertionOfJUnitTest`
- Added `containsLineHitter` method to `LineHitterTest`
- Added line hitter related tests

> The following files were skipped due to too many changes: `src/test/java/com/github/lombrozo/testnames/rules/RuleLineHitterTest.java`, `src/main/java/com/github/lombrozo/testnames/rules/RuleLineHitter.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-07-28 12:00 UTC, volodya-lombrozo requested changes
@l3r8yJ First of all, great thanks for your contribution! 

I've left several comments to your implementation, but If you don't have enough time to fix them, I would recommend to use puzzles (like you did with the documentation) to show, that all the  "requested changes" will be implemented in the future.

2023-07-28 13:50 UTC, l3r8yJ commented
@volodya-lombrozo good suggestions, I'll fix it a bit later

2023-08-01 23:51 UTC, l3r8yJ commented
@volodya-lombrozo take a look again, please 

fixed all, maybe didn't notice something

2023-08-02 09:06 UTC, l3r8yJ commented on src/test/java/com/github/lombrozo/testnames/rules/RuleAssertTrueHitterTest.java
> +        final Assertion assertion = Mockito.mock(Assertion.class);
@volodya-lombrozo Yes, I tried using `Assertion.Fake`, but if you make a fake method in the `isLineHitter` method that returns `true`, it breaks the other tests, as the number of complaints increases by one, and it breaks assertions in other tests

I see two options here, mokito or anonymous class, what do you think?

2023-08-02 09:55 UTC, volodya-lombrozo commented on src/test/java/com/github/lombrozo/testnames/rules/RuleAssertTrueHitterTest.java
> +        final Assertion assertion = Mockito.mock(Assertion.class);
@l3r8yJ You can just add a little bit code to the `Assertion.Fake`, something like the next:
```java
 class Fake implements Assertion {
        private final String message;
        private final boolean hitter;

        public Fake() {
            this(UUID.randomUUID().toString());
        }

        public Fake(final String msg) {
           this(msg, false);
        }

        public Fake(final String msg, final boolean hitter) {
            this.message = msg;
            this.hitter = hitter;
        }
    }
```
Then, in the required test you can just invoke `new Assertion.Fake("something", true);

2023-08-02 10:55 UTC, l3r8yJ commented
@volodya-lombrozo take a look, please

2023-08-02 11:40 UTC, volodya-lombrozo commented
@rultor merge

2023-08-02 11:43 UTC, rultor commented
> @rultor merge

@volodya-lombrozo OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/33796-1662053771)

2023-08-02 11:45 UTC, merged

2023-08-02 11:46 UTC, rultor commented
> @rultor merge

@volodya-lombrozo Done! FYI, the full log is [here](https://www.rultor.com/t/33796-1662053771) (took me 3min)

2023-08-02 12:31 UTC, volodya-lombrozo commented
@rultor release, tag is `1.1.0`, title is `1.1.0`

2023-08-02 12:34 UTC, rultor commented
> @rultor release, tag is `1.1.0`, title is `1.1.0`

@volodya-lombrozo OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/33796-1662125877)

2023-08-02 12:37 UTC, rultor commented
> @rultor release, tag is `1.1.0`, title is `1.1.0`

@volodya-lombrozo Done! FYI, the full log is [here](https://www.rultor.com/t/33796-1662125877) (took me 3min)