254: line hitter docs
volodya-lombrozo/jtcop pull request #295
Opened 2023-11-22 15:40 UTC by l3r8yJ

closes #254

@volodya-lombrozo take a look, please

2023-11-23 08:21 UTC, volodya-lombrozo requested changes
@l3r8yJ Thank you for the contribution. Just one small comment.

2023-11-23 08:21 UTC, volodya-lombrozo commented on docs/rules/line-hitter.md
> +```java
@l3r8yJ, it isn't clear from the description whether it is an example of how to **do** something or how **not to do** it. Could you provide two different examples, one labeled 'Bad' and the other 'Good' (or something similar)? This way, I will understand what to do more quickly without the need to read the text description.

2023-11-24 00:38 UTC, l3r8yJ commented
@volodya-lombrozo take a look, please

2023-11-24 07:04 UTC, volodya-lombrozo approved these changes
@l3r8yJ Looks good to me. Thank you.

2023-11-24 07:04 UTC, volodya-lombrozo commented
@rultor merge

2023-11-24 08:27 UTC, volodya-lombrozo commented
@rultor merge

2023-11-24 08:29 UTC, rultor commented
> @rultor merge

@volodya-lombrozo OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/36642-1825229861)

2023-11-24 08:31 UTC, merged

2023-11-24 08:31 UTC, rultor commented
> @rultor merge

@volodya-lombrozo Done! FYI, the full log is [here](https://www.rultor.com/t/36642-1825229861) (took me 3min)

2023-11-24 08:34 UTC, rultor commented
> @rultor merge

@l3r8yj @volodya-lombrozo The pull request is closed already, so I can't merge it

2023-11-24 08:34 UTC, rultor commented
> @rultor merge

@volodya-lombrozo I'm sorry, I don't understand you :( Check [this page](https://doc.rultor.com/basics.html) and try again please